#!/bin/sh
LD_LIBRARY_PATH=.libs
DYLD_LIBRARY_PATH="$LD_LIBRARY_PATH"
LUA_CPATH='.libs/?.so'
LUA_PATH='./?.lua;./etc/?.lua;./etc/?/init.lua'
export LD_LIBRARY_PATH DYLD_LIBRARY_PATH LUA_CPATH LUA_PATH
exec lua $*
