#!/bin/sh
LD_LIBRARY_PATH=.libs
DYLD_LIBRARY_PATH="$LD_LIBRARY_PATH"
RCLUA_CPATH='.libs/?.so'
RCLUA_PATH='./?.lua;./etc/?.lua;./etc/?/init.lua'
case `uname` in
	Darwin)
	  dsymutil=" --dsymutil=yes"
	  ;;
esac
export LD_LIBRARY_PATH DYLD_LIBRARY_PATH RCLUA_CPATH RCLUA_PATH
exec valgrind --tool=memcheck --vex-iropt-precise-memory-exns=yes --leak-check=full $dsymutil --num-callers=48 --track-origins=yes --show-reachable=yes --log-file=/var/tmp/thrlua.log .libs/rclua $*
